const contentData = [
  {
    id: 1,
    name: "Reimbursement",
    description: "paid by Samo",
    price: 60,
    date: "06.03.2021",
  },
  {
    id: 2,
    name: "Reimbursement",
    description: "paid by Adam",
    price: 32,
    date: "06.03.2021",
  },
  {
    id: 3,
    name: "Reimbursement",
    description: "paid by Lepis",
    price: 55,
    date: "06.03.2021",
  },
  {
    id: 4,
    name: "Parking",
    description: "paid by Klaudia",
    price: 55,
    date: "06.03.2021",
  },
  {
    id: 5,
    name: "Redbull",
    description: "paid by Jakub",
    price: 2,
    date: "06.03.2021",
  },
  {
    id: 6,
    name: "Coca Cola",
    description: "paid by Samo",
    price: 1.5,
    date: "06.03.2021",
  },
  {
    id: 7,
    name: "Trajekt",
    description: "paid by Peto",
    price: 1000,
    date: "06.03.2021",
  },
  {
    id: 1,
    name: "Reimbursement",
    description: "paid by Samo",
    price: 60,
    date: "06.03.2021",
  },
  {
    id: 2,
    name: "Reimbursement",
    description: "paid by Adam",
    price: 32,
    date: "06.03.2021",
  },
  {
    id: 3,
    name: "Reimbursement",
    description: "paid by Lepis",
    price: 55,
    date: "06.03.2021",
  },
  {
    id: 4,
    name: "Parking",
    description: "paid by Klaudia",
    price: 55,
    date: "06.03.2021",
  },
  {
    id: 5,
    name: "Redbull",
    description: "paid by Jakub",
    price: 2,
    date: "06.03.2021",
  },
  {
    id: 6,
    name: "Coca Cola",
    description: "paid by Samo",
    price: 1.5,
    date: "06.03.2021",
  },
  {
    id: 7,
    name: "Trajekt",
    description: "paid by Peto",
    price: 1000,
    date: "06.03.2021",
  },
];

export default contentData;
